name: build and release extension

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: create zip file
        run: |
          zip -r minimal-newtab.zip . \
            -x ".git/*" \
            -x ".github/*"

      - name: create github release
        uses: softprops/action-gh-release@v2
        with:
          files: minimal-newtab.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}